name: fledge

on:
  # for manual triggers
  workflow_dispatch:
  # daily run
  schedule:
  - cron: "30 14 * * *"

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install fledge
        run: Rscript -e 'install.packages("fledge")'

      - name: Bump version
        run: Rscript -e 'fledge::bump_version(which = "dev")'
